### PR TITLE
Adds placeholders for guides with important info about token standard upgrades.

### PR DESCRIPTION
**Pull request by joshuahannan**
I thought it would be a good idea to have placeholders for the FT and NFT migration guides that included important info about where to find the FLIPs and code for the token standards and what the import addresses are for all the contracts. I also included this for the core contracts.

This will still be useful to people until we get the full guides finished, so I'd like to get this merged soon so we can have it up there while I work on the actual guides.

I'm not sure if I got the config right to display the organization properly on the sidebars and such, so I might need help with that. I wanted the guides to be their own section in the site, just like `language` and `tutorial` are.

### CODE REVIEW

**Comment by joshuahannan** [comment]
@bthaile @nialexsan Do either of y'all know what I need to do to make the deployment work? I tried to add a new folder for the migration guides, but something went wrong with the deployment. I'd really like to get this merged soon we can share it with developers

**Comment by gregsantos** [comment]
@joshuahannan Looks like a couple broken links need to be fixed:

- On source page path = /docs/cadence_migration_guide/:
--
> linking to ./cadence_migration_guide/nft-guide.mdx (resolved as: /docs/cadence_migration_guide/cadence_migration_guide/nft-guide.mdx)
> linking to ./cadence_migration_guide/ft-guide.mdx (resolved as: /docs/cadence_migration_guide/cadence_migration_guide/ft-guide.mdx)

**Comment by joshuahannan** [comment]
okay, I fixed the links. Is there anything we need to do to update the banner at the top of the site and the developers.onflow.org site to make sure the link goes to the right page? Since I changed the migration guide to a folder, I don't know if that will break those links

**Comment by Aliserag** [comment]
About the Banner, for now [we're toning it down](https://github.com/onflow/docs/pull/556) and linking it to the Cadence 1.0 website [page](https://flow.com/upgrade/cadence-1) which will lead to the migration. We're also going to try expanding the banner to other ecosystem partners and major dev tools sites

**Comment by Aliserag** [comment]
- Typo in FT doc -"locaed" 
- Would link to Bastian's post "We are assuming that you are somewhat familiar with the [Cadence 1.0 changes](https://forum.flow.com/t/update-on-cadence-1-0/5197)"

**Review by Aliserag — APPROVED** [review]

**Pull request merged**
